server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: volkan
    url: jdbc:mysql://localhost:3306/locking
  jpa:
    show-sql: true
    properties:
      #Enable  Query Cache
      hibernate:
        cache:
          use_query_cache: true
      javax:
        persistence:
          sharedCache:
            #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
            mode: ENABLE_SELECTIVE
    hibernate:
      #optional - enable SQL statements formatting.
      format_sql: true
      #optional - generate statistics to check if L2/query cache is actually being used.
      generate_statistics: true
      cache:
        #required - turn on L2 cache.
        use_second_level_cache: true
        #optional - turn on query cache.
        use_query_cache: true
        region:
          #required - classpath to cache region factory.
          factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

management:
  endpoints:
    enabled-by-default: true

logging:
  level:
    #web: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.cache: DEBUG
